# Generated by Django 3.2.15 on 2022-09-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='dislikes',
        ),
    ]
